/** Imagem padrão se a foto do veículo não carregar */
const CAR_IMAGE_FALLBACK = "assets/images/catalog/audi-tts-2023.webp";

const CARS = [
  {
    id: 1,
    brand: "BMW",
    model: "320i M Sport",
    year: 2022,
    km: 28000,
    fuel: "Gasolina",
    transmission: "Automático",
    category: "sedan",
    price: 189900,
    tag: "Destaque",
    image: "assets/images/catalog/bmw-320i-m-sport.webp",
    description:
      "Pacote M Sport, teto solar e interior em couro. Revisões em concessionária, único dono.",
  },
  {
    id: 2,
    brand: "Audi",
    model: "Q5 2.0 TFSI",
    year: 2021,
    km: 42000,
    fuel: "Gasolina",
    transmission: "Automático",
    category: "suv",
    price: 245000,
    tag: "SUV",
    image: "assets/images/catalog/audi-q5-2021.webp",
    description:
      "Quattro, faróis Matrix LED e painel Virtual Cockpit. Excelente para família e viagens.",
  },
  {
    id: 4,
    imageDivider: true,
    brand: "Jeep",
    model: "Compass Limited",
    year: 2020,
    km: 51000,
    fuel: "Diesel",
    transmission: "Automático",
    category: "suv",
    price: 132500,
    tag: "Aventura",
    image: "assets/images/catalog/jeep-compass-limited.webp",
    description:
      "Tração 4x4, bom torque e acabamento premium. Ideal para cidade e estrada de terra.",
  },
  {
    id: 7,
    brand: "Mercedes-Benz",
    model: "C180 Avantgarde",
    year: 2018,
    km: 62000,
    fuel: "Gasolina",
    transmission: "Automático",
    category: "sedan",
    price: 178000,
    tag: "Luxo",
    image: "assets/images/catalog/mercedes-c180.webp",
    description:
      "Elegância Mercedes com pacote Avantgarde. Interior impecável e revisões em dia.",
  },
  {
    id: 8,
    brand: "Toyota",
    model: "Hilux SRX",
    year: 2021,
    km: 55000,
    fuel: "Diesel",
    transmission: "Automático",
    category: "pickup",
    price: 289000,
    tag: "Pickup",
    image: "assets/images/catalog/toyota-hilux-srx.webp",
    description:
      "Versão topo SRX, 4x4 e multimídia completa. Referência em retenção de valor.",
  },
  {
    id: 9,
    brand: "Hyundai",
    model: "Creta Ultimate",
    year: 2022,
    km: 22000,
    fuel: "Flex",
    transmission: "Automático",
    category: "suv",
    price: 124900,
    tag: "Seminovo",
    image: "assets/images/catalog/hyundai-creta-ultimate.webp",
    description:
      "Baixa quilometragem, garantia de fábrica remanescente e pacote Ultimate completo.",
  },
  {
    id: 10,
    brand: "Nissan",
    model: "Kicks Advance 1.6",
    year: 2022,
    km: 31000,
    fuel: "Flex",
    transmission: "Automático",
    category: "suv",
    price: 115900,
    tag: "Econômico",
    image: "assets/images/catalog/nissan-kicks-advance.webp",
    description:
      "Pacote Advance com câmera 360° e central multimídia. Único dono e IPVA em dia.",
  },
  {
    id: 11,
    brand: "Honda",
    model: "Civic Touring",
    year: 2020,
    km: 39000,
    fuel: "Gasolina",
    transmission: "Automático",
    category: "sedan",
    price: 128900,
    tag: "Top",
    image: "assets/images/catalog/honda-civic-touring.webp",
    description:
      "Honda Sensing, teto solar e acabamento Touring. Impecável por dentro e por fora.",
  },
  {
    id: 12,
    brand: "Audi",
    model: "TTS",
    year: 2023,
    km: 25000,
    fuel: "Gasolina",
    transmission: "Automático",
    category: "hatch",
    price: 150000,
    tag: "Esportivo",
    image: "assets/images/catalog/audi-tts-2023.webp",
    description:
      "Audi TTS com acabamento esportivo, tração quattro e motor turbo. Foto real do veículo em estoque.",
  },
  {
    id: 13,
    brand: "Porsche",
    model: "Macan S",
    year: 2022,
    km: 34000,
    fuel: "Gasolina",
    transmission: "Automático",
    category: "suv",
    price: 318000,
    tag: "Luxo",
    image: "assets/images/catalog/porsche-macan-s.webp",
    description:
      "Pacote S, suspensão adaptativa e interior em couro. Histórico de revisões na rede Porsche.",
  },
  {
    id: 14,
    brand: "Lexus",
    model: "ES 300h Luxury",
    year: 2021,
    km: 36000,
    fuel: "Híbrido",
    transmission: "Automático",
    category: "sedan",
    price: 242000,
    tag: "Híbrido",
    image: "assets/images/catalog/lexus-es-300h-luxury.webp",
    description:
      "Sedan híbrido silencioso, pacote Luxury e baixo consumo. Conforto executivo e tecnologia Lexus.",
  },
  {
    id: 15,
    brand: "Ford",
    model: "Ranger Limited",
    year: 2020,
    km: 58000,
    fuel: "Diesel",
    transmission: "Automático",
    category: "pickup",
    price: 278000,
    tag: "Pickup",
    image: "assets/images/catalog/ford-ranger-limited.webp",
    description:
      "Cabine dupla Limited, 4x4 e multimídia SYNC. Ideal para trabalho pesado e lazer.",
  },
];
